name: 'Filter SARIF'
description: 'Filter SARIF results by path'
inputs:
  patterns:
    description: 'Patterns for the results to remove. If a pattern starts with "-", it is an exclusion pattern, otherwise, it is an inclusion pattern.'
    required: true
  input:
    description: 'Path to the input SARIF file'
    required: true
  output:
    description: 'Path to the output SARIF file'
    required: true
runs:
  using: "composite"
  steps:
    - name: Subscription check
      run: |
        # validate subscription status
        API_URL="https://agent.api.stepsecurity.io/v1/github/$GITHUB_REPOSITORY/actions/subscription"

        # Set a timeout for the curl command (3 seconds)
        RESPONSE=$(curl --max-time 3 -s -w "%{http_code}" "$API_URL" -o /dev/null) || true
        CURL_EXIT_CODE=${?}

        # Check if the response code is not 200
        if [ $CURL_EXIT_CODE -ne 0 ]; then
          echo "Timeout or API not reachable. Continuing to next step."
        elif [ "$RESPONSE" = "200" ]; then
          :
        elif [ "$RESPONSE" = "403" ]; then
          echo "Subscription is not valid. Reach out to support@stepsecurity.io"
          exit 1
        else
          echo "Timeout or API not reachable. Continuing to next step."
        fi
      shell: bash

    - name: filter
      run: |
        unset LD_PRELOAD
        python3 "$GITHUB_ACTION_PATH/filter_sarif.py" --input "${{ inputs.input }}" --output "${{ inputs.output }}" --split-lines -- "${{ inputs.patterns }}"
      shell: bash
