name: "Action Test"
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      pattern1:
        description: 'Include or exclude pattern'
        required: true
      pattern2:
        description: 'Include or exclude pattern'
        required: false
      pattern3:
        description: 'Include or exclude pattern'
        required: false
      pattern4:
        description: 'Include or exclude pattern'
        required: false

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@51f77329afa6477de8c49fc9c7046c15b9a4e79d # v3.29.5
      with:
        languages: ${{ matrix.language }}

    - run: |
        javatest/build

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@51f77329afa6477de8c49fc9c7046c15b9a4e79d # v3.29.5
      with:
        upload: failure-only
        output: sarif-results

    - name: filter-sarif
      uses: ./
      with:
        #patterns: |
        #  -**/*.java
        #  +**/*Exposed*
        patterns: |
          ${{ github.event.inputs.pattern1 }}
          ${{ github.event.inputs.pattern2 }}
          ${{ github.event.inputs.pattern3 }}
          ${{ github.event.inputs.pattern4 }}
        input: sarif-results/java.sarif
        output: sarif-results/java.sarif

    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@51f77329afa6477de8c49fc9c7046c15b9a4e79d # v3.29.5
      with:
        sarif_file: sarif-results/java.sarif

    - name: Upload loc as a Build Artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: sarif-results
        path: sarif-results
        retention-days: 1
